namespace: rust-rest-dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: rust-rest
  newName: image-registry.openshift-image-registry.svc:5000/rust-rest-build/rust-rest
  newTag: e8763a5052ce7b4df4d5420aa92dc166a8ce1491
patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/name
      value: rust-rest-dev
  target:
    kind: Namespace
    name: rust-rest-base
    version: v1
