namespace: rust-rest-dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: rust-rest
  newName: image-registry.openshift-image-registry.svc:5000/rust-rest-dev/rust-rest
  newTag: b4c34be
