namespace: rust-rest-dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: rust-rest
  newName: rust-rest
  newTag: b4c34be
patchesJSON6902:
- target:
    version: v1
    kind: Namespace
    name: rust-rest-base
  patch: |-
    - op: replace
      path: /metadata/name
      value: rust-rest-dev
